### PR TITLE
Technology 2015 01 22

### PR DESCRIPTION
**Pull request by tladendo**

### CODE REVIEW

**Comment by thabofletcher** [comment]
Hey @tladendo just trying to clean up a bit - this doesn't seem to have ever made it into the wild. You want me to merge this into dev?

**Comment by tladendo** [comment]
so this is to redirect people who registered from arena back from arena...so maybe @mdesiderio would know if we still need this?

**Comment by mdesiderio** [comment]
@thabofletcher are you saying this was never deployed? If so, I think we can forget about it.

**Comment by thabofletcher** [comment]
@mdesiderio @tladendo - Ok I looked into the original issue and looks like there is no reason it shouldn't have been deployed, and well thought it was fixed. I think I should merge this guy into dev.

https://appirio.my.salesforce.com/a41500000000n3N?srPos=0&srKp=a41

**Comment by tladendo** [comment]
@thabofletcher -- i'm fine with you merging. it's your call.

**Pull request merged**
