### PR TITLE
Improve challenge visibility control: getChallenge and getRegistrants

### PR DESCRIPTION
**Pull request by TheOsch**
Improve challenge visibility control: getChallenge and getRegistrants

I removed one field from the `check_is_related_with_challenge` query. Besides `getChallenge` there are two other functions in `actions/challenges.js` that use this query: `getSubmissions` and `getPhases`. These two functions use this query only to check the eligibility. I decided to take the liberty of fixing them too. So now six more actions work according to the new logic: getChallenge, getSoftwareChallenge, getStudioChallenge (all these three actions in fact consist of a simple call to the same function - getChallenge), getRegistrants, getSubmissions and getRoles.
Postman tests are provided for getChallenge, getRegistrants, getSubmissions and getRoles actions.

### CODE REVIEW

**Comment by skyhit** [comment]
@TheOsch thanks, looks good, after fixing this, what endpoints are left for challenges?

**Comment by TheOsch** [comment]
I saw you have changed a number of queries by adding a group id check there. I think now first it would be good to update all places where these queries are used and remove toese checks, wouldn't it? I think I can make it in a day.

**Comment by TheOsch** [comment]
It may appear that this operation will empty our list of endpoints to change leaving only those that were included there by mistake.

**Comment by TheOsch** [comment]
By the way, is there an endpoint in V3 that returns a list of groups the given user belongs to? It would be very useful.

**Comment by ajefts** [comment]
Yes, you can do this:  https://api.topcoder-dev.com/v3/groups?memberId=######&membershipType=user

**Comment by TheOsch** [comment]
@ajefts I couldn't get a valid auth token to call the service. Can you please show me a sample output of this call?

**Comment by ajefts** [comment]
Sure.

```
{
    "id": "25ab1528:15cc0ff4067:1c6a",
    "result": {
        "success": true,
        "status": 200,
        "metadata": null,
        "content": [
            {
                "id": "20000000",
                "modifiedBy": "8547899",
                "modifiedAt": "2017-05-25T09:31:10.000Z",
                "createdBy": "8547899",
                "createdAt": "2017-05-25T09:31:10.000Z",
                "name": "Group Name",
                "description": "Overall XYZ Group"
            }
        ]
    },
    "version": "v3"
}

```

**Comment by TheOsch** [comment]
@ajefts Thank you

**Comment by TheOsch** [comment]
@skyhit 
Bad news: I was too presumptuous when told that I can complete everything in one day. I need one more day, will do a PR tomorrow
Good news: I checked the entire list and explored the source code of every 'suspicious' endpoiont. That PR willl be really the last one in this series, it will cover everything.

**Comment by skyhit** [comment]
@TheOsch ok, that is fine.

**Comment by TheOsch** [comment]
Made a PR on Friday bit forgot to notify you. Did you notice it?

**Comment by skyhit** [comment]
@TheOsch you mean https://github.com/appirio-tech/tc-api/pull/508?

**Comment by TheOsch** [comment]
Yes

**Comment by skyhit** [comment]
@TheOsch ok, I will review that

**Comment by TheOsch** [comment]
I had to tell you 3 days ago but I thought you'll be automatically notified about it. Sorry.

**Comment by skyhit** [comment]
@TheOsch some of the changes seems already applied, can you merge latest dev? so I can see the difference clearly?

**Comment by TheOsch** [comment]
The latest commit to dev was earlier than the PR, and I merged just before pushing. Right now the attempt to merge results in 'Already up-to-date.' message, and status reports there's nothing to commit.

**Comment by TheOsch** [comment]
Which changes are suspicious?

**Pull request merged**
